### ISSUE TITLE
Add EXTRACT_ALL and EXTRACT_MEMBERS in documentation

### ISSUE THREAD

**Issue by ilyaZar** [smrfeld/cpp_doxygen_sphinx#2]
Hey, first of all great blog posts, I really enjoyed your entertaining way of writing.

The following "issue" may be platform dependent and/or depends on the doxygen version.

I was not able to build the docs properly in html until I figured out I need:

`EXTRACT_ALL = YES`
`EXTRACT_PRIVATE = YES`

which may be per default on your platform but was not on my Linux Mint 20. See https://www.doxygen.nl/manual/faq.html.

Maybe you want to add this to the documentation as some my actually stumble over this, particularly if they are new to doxygen or c++ (where per default members are private, hence the second flag).

EDIT: by properly I mean only the class name appeared but members were undocumented.

**Comment by smrfeld** [comment]
Thanks for figuring this out, I added it also to Medium.
